mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^zhihu/', include('zhihu.urls')),
]

zhihu/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login, logout
from zhihu import views
app_name = 'zhihu'
urlpatterns = [
    url(r'^$', views.login, name='login'),
    url(r'^login/$', views.login, name='login'),
    url(r'^reg/$', views.reg, name='reg'),
    url(r'^index/$', views.index, name='index'),
    url(r'^active/(?P<token>(.*))/$', views.active, name='active'),
    url(r'^logout_view/$', views.logout_view, name='logout_view'),
    url(r'^post_question/(?P<id>[0-9]+)/$',
        views.post_question, name='post_question'),
    url(r'^create_question/$', views.create_question, name='create_question'),
    url(r'^personal/$', views.personal, name='personal'),
    url(r'^forget_pwd/$', views.forget_pwd, name='forget_pwd'),
    url(r'^reset_pwd/$', views.reset_pwd, name='reset_pwd'),
]

zhihu/models.py
from django.db import models
from django.contrib.auth.models import User
#from django.utils import timezone
#from datetime import datetime
# Create your models here.


# class User(models.Model):
#     name = models.CharField(max_length=60)
#     email = models.CharField(max_length=60, unique=True)
#     password = models.CharField(max_length=60)

#     def __str__(self):
#         return self.name
class UserPersonal(models.Model):
    user = models.OneToOneField(User)
    signature = models.CharField(max_length=60)
    area = models.CharField(max_length=50, blank=True)
    sex = models.CharField(max_length=30, blank=True)


class Question(models.Model):
    title = models.CharField(max_length=255)
    content = models.CharField(max_length=5000)
    user = models.ForeignKey(User)
    updatedate = models.CharField(max_length=255)


class Comment(models.Model):
    content = models.CharField(max_length=1000)
    user = models.ForeignKey(User)
    question = models.ForeignKey(Question)
    updatedate = models.CharField(max_length=255)

zhihu/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

# Create your views here.
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from zhihu.models import Question, Comment, UserPersonal

from django.urls import reverse
from django.contrib.auth import authenticate, login as loginin, logout
from itsdangerous import URLSafeSerializer
from django.conf import settings as django_settings
from django.core.mail import EmailMultiAlternatives,  EmailMessage
from django.contrib import messages
from django.template import loader, Context
import threading


def run_thread(msg):
    msg.send()


def send_mail(subject, to, from_email, html_content):
    msg = EmailMessage(subject, html_content, from_email, to)
    # msg.attach_alternative(html_content, 'text/html')
    msg.content_subtype = "html"
    # msg.send()
    thr = threading.Thread(target=run_thread, args=(msg,))
    thr.start()
    return thr


def login(request):
    if request.method == 'POST':
        username = request.POST['email']
        password = request.POST['password']
        user_exist = User.objects.get(username=username)
        user = authenticate(username=username, password=password)
        if user is not None:
            loginin(request, user)
            #messages.add_message(request, messages.SUCCESS, '登录成功，体验愉快')
            return redirect(reverse('zhihu:index'))
        elif user_exist is not None and user is None:
            messages.add_message(request, messages.SUCCESS, '未激活')
            return redirect(reverse('zhihu:login'))
        else:
            return redirect(reverse('zhihu:reg'))
    else:
        return render(request, 'zhihu/login.html')


def logout_view(request):
    logout(request)
    return render(request, 'zhihu/login.html')


def reg(request):
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']
        username = request.POST['name']
        user_exist = User.objects.filter(username=username)

        if user_exist:
            messages.add_message(request, messages.ERROR, '用户名已经被注册')
            return render(request, 'zhihu/reg.html')

        query = User.objects.create_user(
            email=email, password=password, username=username)
        query.is_active = False
        query.save()
        token = token_confirm.generate_token(username)
        context = {'username': username,
                   'token': request.build_absolute_uri(
                       reverse('zhihu:active', args=[token, ])),
                   'info': '欢迎你注册草乎，请点击下面链接激活你的账户', }
        t = loader.get_template('zhihu/email.html')
        html_content = t.render(Context(context))

        send_mail('草乎认证邮件', [email],
                  django_settings.EMAIL_HOST_USER, html_content)
        messages.add_message(request, messages.SUCCESS, '注册成功，请前往邮箱进行激活后登录')

        return redirect(reverse('zhihu:login'))
    else:
        return render(request, 'zhihu/reg.html')

import time as tt


def format_time(time):
    print(tt.strftime('%Y-%m-%d %H:%M:%S', time))
    return tt.strftime('%Y-%m-%d %H:%M:%S', time)


@login_required(login_url='/zhihu/login/')
def index(request):
    if request.user.is_authenticated():
        if request.method == 'POST':
            title = request.POST['title']
            content = request.POST['question']
            if title != '':
                user = User.objects.get(username=request.user.username)
                updatetime = format_time(tt.localtime())
                insert = user.question_set.create(
                    title=title, content=content, updatedate=updatetime)
                insert.save()
        username = request.user.username
        latest_question = Question.objects.order_by('id')[::-1]
        # print(latest_question[0].user.userpersonal.signature)
        context = {
            'latest_question': latest_question,
            'name': username,
        }
        return render(request, 'zhihu/index.html', context)
    else:
        messages.add_message(request, messages.SUCCESS, '激活成功，欢迎登录')
        return HttpResponseRedirect(reverse('zhihu:login'))


def active(request, token):
    try:
        username = token_confirm.confirm_token(token)
    except:
        username = token_confirm.remove_token(token)
        user = User.objects.filter(username)
        for i in user:
            user.delete()
        return render(request, 'zhihu/reg.html')

    try:
        user = User.objects.get(username=username)
    except User.DoesNotExist:
        return render(request, 'zhihu/reg.html')
    user.is_active = True
    user.save()
    messages.add_message(request, messages.SUCCESS, '激活成功，欢迎登录')
    return redirect(reverse('zhihu:login'))


class Token:

    def __init__(self, secret_key):
        self.secret_key = secret_key
        # self.email = email

    def generate_token(self, email):
        s = URLSafeSerializer(self.secret_key)
        token = s.dumps(email)
        return token

    def confirm_token(self, token):
        s = URLSafeSerializer(self.secret_key)
        result = s.loads(token)
        return result

    def remove_token(self, token):
        s = URLSafeSerializer(self.secret_key)
        return s.loads(token)

    # def remove_token(self, token):
token_confirm = Token(django_settings.SECRET_KEY)


def post_question(request, id):
    # if request.method == 'POST':
    #     title = request.POST['title']
    #     content = request.POST['question']
    #     if title != '':
    #         user = User.objects.get(username=request.user.username)
    #         updatetime = format_time(tt.localtime())
    #         insert = user.question_set.create(
    #             title=title, content=content, updatedate=updatetime)
    #         insert.save()
    #     return redirect(reverse('zhihu:index'))
    if request.method == 'POST':
        comment = request.POST['comment']
        user = User.objects.get(username=request.user.username)
        post = Question.objects.get(pk=id)
        query = Comment.objects.create(
            content=comment, user=user, question=post, updatedate=format_time(tt.localtime()))
    post = Question.objects.get(pk=id)
    answer_query = Comment.objects.filter(question=id).order_by('-updatedate')
    answer_quantity = answer_query.count()
    return render(request, 'zhihu/question.html', {'post': post, 'quantity': answer_quantity, 'answers': answer_query})


@login_required
def create_question(request):
    return render(request, 'zhihu/create_question.html')


@login_required
def personal(request):
    user_id = request.user.id
    query = User.objects.get(pk=user_id)
    # signature = query.userpersonal.signature
    # area = query.userpersonal.area

    if request.method == 'POST':
        personal_signature = request.POST['signature']
        personal_area = request.POST['area']
        sex = request.POST.get('sex', False)

        if user_id:
            #query = User.objects.get(pk=user_id)
            #validate_exists = UserPersonal.objects.get(user_id=user_id)
            if UserPersonal.objects.filter(user=query):
                validate_exists = UserPersonal.objects.filter(user=query)
                validate_exists.delete()
            temp = UserPersonal(signature=personal_signature,
                                user=query, area=personal_area, sex=sex)
            temp.save()
    try:
        signature = query.userpersonal.signature
        area = query.userpersonal.area
        sex = query.userpersonal.sex
    except:
        signature = ''
        area = ''
        sex = ''

    return render(request, 'zhihu/personal.html', {'signature': signature, 'area': area, 'sex': sex})


# @login_required
# def comment(request, id):
#     if request.method == 'POST':
#         comment = request.POST['comment']
#         user = User.objects.get(username=request.user.username)
#         post = Question.objects.get(pk=id)
#         query = Comment.objects.create(
#             content=comment, user=user, question=post, updatedate=format_time(tt.localtime()))
#     return render(request, 'zhihu/comment.html', {'id': id})

def forget_pwd(request):
    if request.method == 'POST':
        email = request.POST['email']
        query = User.objects.filter(email=email)
        if query is not None:
            token = token_confirm.generate_token(email)
            context = {'username': '',
                       'token': request.build_absolute_uri(
                           reverse('zhihu:active', args=[token, ])),
                       'info': '点击下面链接修改密码', }
            t = loader.get_template('zhihu/email.html')
            html_content = t.render(Context(context))

            send_mail('草乎认证邮件', [email],
                      django_settings.EMAIL_HOST_USER, html_content)
            messages.add_message(
                request, messages.SUCCESS, '注册成功，请前往邮箱进行激活后登录')
    return render(request, 'zhihu/forget_pwd.html')


def reset_pwd(request):
    return render(request, 'zhihu/reset_pwd.html')

zhihu/templates/zhihu/confirm_pwd.html
{% extends 'content.html' %}
{% block title %}设置{% endblock %}
{% block nav %}
{{block.super}}
{% endblock %}
<style>
    .form-control{width:800px;}
</style>
{% block content %}


    <div class="col-sm-8 content-margin">
        {% if messages %}
          <ul class="alert alert-success">
        {% for message in messages %}
              {{message}}
        {% endfor %}</ul>
        {% endif %}


        <form action="{% url 'zhihu:forget_pwd' %}" method='post'>
        {% csrf_token %}
        <h5>修改密码</h5>
            <input  type="text" class="form-control col-sm-2" id="inputEmail3" name='email' placeholder="请输入你的新密码" >
        
            <button style="float:right;margin-top:15px;" type="submit" class="btn btn-primary btn-lg"><font size=3>提交</font></button>
        </form>
    </div>
</div>
{% endblock %}

zhihu/templates/zhihu/create_question.html
{% extends 'content.html' %}
{% block title %}创建新问题{% endblock %}
{% block nav %}
{{block.super}}
{% endblock %}

{% block content %}
<div class="content-margin" style="width:800px;">
    <form action="{% url 'zhihu:index' %}" method='post'>
    {% csrf_token %}
    <input class="form-control" type="text" name="title" placeholder="请输入你的问题"><br>
    <textarea class="form-control" rows="3 type="text" name="question" placeholder="请输入问题详细描述"></textarea><br>
      <div style="float:right"><button type="submit" class="btn btn-primary btn-lg"><font size=3>提交</font></button>
      </div>
    </form>
</div>
      



{% endblock %}

zhihu/templates/zhihu/email.html
<h3>{{username}}</h3>{{info}}
<h3><a href="{{token}}">点击此处</a></h3>

zhihu/templates/zhihu/forget_pwd.html
{% extends 'content.html' %}
{% block title %}设置{% endblock %}
{% block nav %}
{{block.super}}
{% endblock %}
<style>
    .form-control{width:800px;}
</style>
{% block content %}


    <div class="col-sm-8 content-margin">
        {% if messages %}
          <ul class="alert alert-success">
        {% for message in messages %}
              {{message}}
        {% endfor %}</ul>
        {% endif %}


        <form action="{% url 'zhihu:forget_pwd' %}" method='post'>
        {% csrf_token %}
        <h5>修改密码</h5>
            <input  type="text" class="form-control col-sm-2" id="inputEmail3" name='email' placeholder="请输入你的注册邮箱" >
        
            <button style="float:right;margin-top:15px;" type="submit" class="btn btn-primary btn-lg"><font size=3>提交</font></button>
        </form>
    </div>
</div>
{% endblock %}

zhihu/templates/zhihu/index.html
{% extends 'content.html' %}
{% block title %}Index{% endblock %}
{% block nav %}
{{block.super}}
{% endblock %}

{% block content %}
      <style>
        *{margin:0;}
        li {list-style-type:none;}
        .title{font-family:"微软雅黑";font-size:25pt;}
        .position{float:left;margin-right:300px;}
        .content {color:#259;font-size:14px;font-weight:700;border-top:1px solid #eee;margin-top:15px;}
        .username {color:inherit;font-size:14px;font-weight:700;}
        .date::before {content:",";}
        .date {color:#999;}
        .main {line-height:1.7;}

      </style>
<div class="container-fluid">
  <div class="row content-margin">
    <div class="col-md-8">
     

      <div>
        <ul class="title">
        <li class="position"><a href="{% url 'zhihu:create_question' %}"><span class="glyphicon glyphicon-plus"></span>&nbsp;提问</a>
        </li>
        <li>
        <span class="glyphicon glyphicon-pencil"></span>&nbsp;写文章</li>
        </ul>
      </div>
    
    {% if latest_question %}
      
        {% for question in latest_question %}
        <div class="main">
        <ul>
          
          <li class="content"><a href="{% url 'zhihu:post_question' question.id %}">{{question.title}}</a></li>
          <li class="username">{{question.user}}
          {% if question.user.userpersonal.signature %}
          <span class="date">{{question.user.userpersonal.signature}},
          {{question.updatedate}}<span>
          {% else %}
          <span class="date">
          {{question.updatedate}}
          {% endif %}
          <span>
          </li>
          <li>内容：{{question.content}}</li>
          <li class="position"><a href={% url "zhihu:post_question" question.id %}>回答</a></li>
          <li>举报</li>
        </ul>
        </div>
        {% empty %}
        <p>当前没有问题</p>
        {% endfor %}
    {% endif %}
    
    </div>

    <div class="col-md-4">
      <ul>
      <li>我的收藏</li>
      <li>我关注的问题</li>
      <li>邀请我回答的问题</li>
      </ul>
    </div>
  </div>
</div>



{% endblock %}

zhihu/templates/zhihu/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}

{% block content %}
{% if messages %}
  <ul class="alert alert-success">
    {% for message in messages %}
      {{message}}
    {% endfor %}</ul>
  {% endif %}
<div>
<div style="margin:auto">
<div class="text-center">
  <h1 style="color:#286090;font-size:50pt">草&nbsp;乎</h1>
  <h2><small>与世界分享你的狗屁经验、见解</small></h2>
  <h4><a href="{% url 'zhihu:reg' %}" class="btn btn-primary btn-sm active" role="button">注册</a>
  <a href="{% url 'zhihu:login' %}" class="btn btn-primary btn-sm active" role="button">登录</a></h4>
</div>
<div class="col-md-offset-5">
<form class="form-horizontal" action="{% url 'zhihu:login' %}" method='post'>
{% csrf_token %}
  <div class="form-group">
<!--     <label for="inputEmail3" class="col-sm-2 control-label">Email</label>
 -->    <div class="col-sm-4">
      <input type="text" class="form-control" id="inputEmail3" name='email' placeholder="用户名" >
    </div>
  </div>
  <div class="form-group">
<!--     <label for="inputPassword3" class="col-sm-2 control-label">Password</label>
 -->    <div class="col-sm-4">
      <input type="password" class="form-control" name="password" id="inputPassword3" placeholder="密码">
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-4">
      <div class="checkbox">
        <label>
          <input type="checkbox"> 记住我
        </label>
        <label> 　　　　　
          <a href="{% url 'zhihu:forget_pwd' %}"><span class="text-right"> 无法登录？</span></a>
        </label>
        <div style="padding-top:10px;"><button  type="submit" class="btn btn-primary btn-block">登录草乎</button></div>
      </div>
    </div>
  </div>
<!--   <div class="form-group">
    <div class="col-sm-10">
      <button type="submit" class="btn btn-default">登录</button>
    </div>
  </div> -->
</form>
</div>
</div>
</div>

{% endblock %}

zhihu/templates/zhihu/personal.html
{% extends 'content.html' %}
{% block title %}设置{% endblock %}
{% block nav %}
{{block.super}}
{% endblock %}
<style>
    .form-control{width:800px;}
</style>
{% block content %}


    <div class="col-sm-8 content-margin">
            <div class="btn-group btn-group-justified">
          <div class="btn-group">
            <a href="{% url 'zhihu:personal'%}"><button type="button" class="btn btn-primary">个人资料</button></a>
          </div>
          <div class="btn-group">
            <a href="{% url 'zhihu:reset_pwd' %}"><button type="button" class="btn btn-primary">账号和密码</button></a>
          </div>
          <div class="btn-group">
            <button type="button" class="btn btn-primary">消息设置</button>
          </div>
        </div>

        <form action="{% url 'zhihu:personal' %}" method='post'>
        {% csrf_token %}
        <h5>个性签名</h5>
            <input  type="text" class="form-control col-sm-2" id="inputEmail3" value="{{signature}}" name='signature' placeholder="一句话描述自己，不超过20个字" > 
        <h5>居住地</h5>
            <input  type="text" class="form-control col-sm-2" id="inputEmail3" value="{{area}}" name='area' placeholder="居住地" >
            <h5>男性：<input type="radio" name="sex" value="male">
            女性：<input  type="radio" name="sex" value="female"></h5>
            <button style="float:right;margin-top:15px;" type="submit" class="btn btn-primary btn-lg"><font size=3>提交</font></button>
        </form>
    </div>
{% endblock %}

zhihu/templates/zhihu/question.html
{% extends 'content.html' %}
{% block title %}Index{% endblock %}
{% block nav %}
{{block.super}}
{% endblock %}
{% block content %}
<style>
        li {list-style-type:none;}
        .title{font-family:"微软雅黑";font-size:25pt;}
        .position{float:left;margin-right:300px;}
        .content {color:#259;font-size:14px;font-weight:700;margin-top:15px;}
        .username {color:inherit;font-size:14px;font-weight:700;}
        .date::before {content:",";}
        .date {color:#999;}
        .main {line-height:1.7;}
        .border{border-top:solid #eee 1px;}

      </style>
<div class="container-fluid">
  <div class="row content-margin">
    <div class="col-md-8">
      <div class="main">
              <ul>
                <li class="content">{{post.title}}</li>
                <li class="username">{{post.user}}<span class="date">{{post.updatedate}}</span></li>
                <li>内容：{{post.content}}</li>
                <div>
                  <h3 class="border">{{quantity}}条回答</h3>
                </div>
                <div>
                  {% for answer in answers %}
                   <div class="border">
                    <li class="username">{{answer.user}}<span class="date">{{answer.updatedate}}<span></li>
                    <li>{{answer.content}}</li>
                   </div>
                  {% endfor %}
                </div>
                <form action="{% url 'zhihu:post_question' post.id %}" method='post'>
                {% csrf_token %}
                  <textarea class="form-control" rows="3" type="text" name="comment" placeholder="请输入答案"></textarea>
                  <button style="float:right;margin-top:15px;" type="submit" class="btn btn-primary btn-lg"><font size=3>提交</font></button>
                </form>
              </ul>
      </div>
    </div>

    <div class="col-md-4">
    <p>呵呵呵</p>
    </div>
  </div>
</div>



{% endblock %}

zhihu/templates/zhihu/reg.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}


{% block content %}

  {% if messages %}
    <ul class="alert alert-warning">
      {% for message in messages %}
        {{message}}
      {% endfor %}</ul>
  {% endif %}
<div style="margin:auto">
<div class="text-center">
  <h1 style="color:#286090;font-size:50pt">草&nbsp;乎</h1>
  <h2><small>与世界分享你的狗屁经验、见解</small></h2>
  <h4><a href="{% url 'zhihu:reg' %}" class="btn btn-primary btn-sm active" role="button">注册</a>
  <a href="{% url 'zhihu:login' %}" class="btn btn-primary btn-sm active" role="button">登录</a></h4>
</div>
<div class="col-md-offset-5">
<form class="form-horizontal" action="{% url 'zhihu:reg' %}" method='post'>
{% csrf_token %}
  <div class="form-group">
<!--     <label for="inputEmail3" class="col-sm-2 control-label">Email</label>
 -->    <div class="col-sm-4">
      <input type="text" class="form-control" id="inputname" name='name' placeholder="名字" >
    </div>
  </div>
    <div class="form-group">
<!--     <label for="inputEmail3" class="col-sm-2 control-label">Email</label>
 -->    <div class="col-sm-4">
      <input type="email" class="form-control" id="inputEmail3" name='email' placeholder="邮箱" >
    </div>
  </div>
  <div class="form-group">
<!--     <label for="inputPassword3" class="col-sm-2 control-label">Password</label>
 -->    <div class="col-sm-4">
      <input type="password" class="form-control" id="inputPassword3" name='password' placeholder="密码">
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-4">
     <!--  <div class="checkbox">
        <label>
          <input type="checkbox"> 记住我
        </label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; -->
        <button type="submit" class="btn btn-primary btn-block ">注册草乎</button>
      </div>
    </div>
  <!-- </div> -->
<!--   <div class="form-group">
    <div class="col-sm-10">
      <button type="submit" class="btn btn-default">登录</button>
    </div>
  </div> -->
</form>
</div>
</div>
{% endblock %}
<h3>hehehehlalalalalla</h3>

zhihu/templates/zhihu/reset_pwd.html
{% extends 'content.html' %}
{% block title %}设置{% endblock %}
{% block nav %}
{{block.super}}
{% endblock %}
<style>
    .form-control{width:800px;margin-top:20px;}
    input{margin-top:20px;}
</style>
{% block content %}


    <div class="col-sm-8 content-margin">
        {% if messages %}
          <ul class="alert alert-success">
        {% for message in messages %}
              {{message}}
        {% endfor %}</ul>
        {% endif %}

    <div class="btn-group btn-group-justified">
        <div class="btn-group">
            <a href="{% url 'zhihu:personal'%}"><button type="button" class="btn btn-primary">个人资料</button></a>
        </div>
        <div class="btn-group">
            <a href="{% url 'zhihu:reset_pwd' %}"><button type="button" class="btn btn-primary">账号和密码</button></a>
        </div>
        <div class="btn-group">
            <button type="button" class="btn btn-primary">消息设置</button>
        </div>
    </div>
        <div class="input1">
        <form action="{% url 'zhihu:reset_pwd' %}" method='post'>
        {% csrf_token %}
        <h5>修改密码</h5>
            <input  type="text" class="form-control col-sm-2" id="inputEmail3" name='email' placeholder="请输入你的注册邮箱" >
            <input  type="password" class="form-control col-sm-2" id="inputEmail3" name='pwd1' placeholder="请输入新密码" >
            <input  type="password" class="form-control col-sm-2" id="inputEmail3" name='pwd2' placeholder="请确认新密码" > 
        
            <button style="float:right;margin-top:15px;" type="submit" class="btn btn-primary btn-lg"><font size=3>提交</font></button>

        </form>
        </div>
    </div>
</div>
{% endblock %}